
const APP_VER = '6.0.9d';
const SW_CACHE = 'hornet-mapper-v5-609d';

/* Map basis */
const map = L.map('map', { zoomControl: true }).setView([52.100, 5.300], 8);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap-bijdragers' }).addTo(map);
map.pm.addControls({ position: 'topleft', drawMarker: false, drawPolyline: false, drawRectangle: true, drawPolygon: true, drawCircle: false, drawCircleMarker: false, editMode: true, dragMode: true, cutPolygon: false, removalMode: true });

/* Statusbar */
const statusSW = document.getElementById('status-sw');
const statusGeo = document.getElementById('status-geo');
const btnSelftest = document.getElementById('btn-selftest');
const btnResetCache = document.getElementById('btn-reset-cache');
function setStatus(el, text, cls){ if(!el) return; el.textContent = text; el.classList.remove('ok','warn','err'); if(cls) el.classList.add(cls); }
function updateSWStatus(){ if(!statusSW) return; const sw=navigator.serviceWorker; const v=APP_VER; const reg=('serviceWorker' in navigator) ? (sw.controller?'actief':'geregistreerd') : 'niet ondersteund'; setStatus(statusSW, `SW:${reg} v${v}`, reg==='niet ondersteund'?'warn':'ok'); }
updateSWStatus();

/* UI refs */
const placeInput = document.getElementById('place-input');
const searchBtn = document.getElementById('search-btn');
const hardDebounceChk = document.getElementById('hard-debounce');
const toggleSidebarBtn = document.getElementById('toggle-sidebar');
const applyFiltersBtn = document.getElementById('apply-filters');
const resetFiltersBtn = document.getElementById('reset-filters');
const saveBtn = document.getElementById('save-btn');
const loadBtn = document.getElementById('load-btn');
const exportBtn = document.getElementById('export-btn');
const importFile = document.getElementById('import-file');
const clearBtn = document.getElementById('clear-btn');
const geocoderSelect = document.getElementById('geocoder-select');
const mapscoKeyInput = document.getElementById('mapsco-key');
const saveSettingsBtn = document.getElementById('save-settings');

/* Debounce */
const SOFT_MS = 180; const HARD_MS = 350; let DEBOUNCE_MS = SOFT_MS; let _lastUiEventTs = 0; function debounceEvent(){ const now=Date.now(); if(now - _lastUiEventTs < DEBOUNCE_MS) return true; _lastUiEventTs = now; return false; } hardDebounceChk?.addEventListener('change', ()=>{ DEBOUNCE_MS = hardDebounceChk.checked ? HARD_MS : SOFT_MS; });

/* Sidebar gedrag */
const SIDEBAR_KEY = 'hornet_sidebar_collapsed_v609d'; function applySidebarCollapsed(collapsed){ if(collapsed){ document.body.classList.add('sidebar-collapsed'); } else { document.body.classList.remove('sidebar-collapsed'); } } function shouldAutoCollapse(){ return window.innerWidth <= 900; } (function initSidebar(){ const saved = localStorage.getItem(SIDEBAR_KEY); const coll = saved === null ? shouldAutoCollapse() : (saved === '1'); applySidebarCollapsed(coll); })(); function setSidebar(coll){ localStorage.setItem(SIDEBAR_KEY, coll?'1':'0'); applySidebarCollapsed(coll); } toggleSidebarBtn?.addEventListener('click', ()=>{ const isColl = document.body.classList.contains('sidebar-collapsed'); setSidebar(!isColl); }); function autoCollapseOnInteraction(){ if(shouldAutoCollapse()) setSidebar(true); } map.on('click', autoCollapseOnInteraction); map.on('touchstart', autoCollapseOnInteraction); map.on('dragstart', autoCollapseOnInteraction); map.on('zoomstart', autoCollapseOnInteraction); window.addEventListener('resize', ()=>{ if(shouldAutoCollapse()) setSidebar(true); });

/* Opslag instellingen */
const SETTINGS_KEY='hornet_settings_v609d'; function loadSettings(){ try{ const s=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}'); return { geocoder:s.geocoder||'photon', mapscoKey:s.mapscoKey||'' }; } catch{ return { geocoder:'photon', mapscoKey:'' }; } } function saveSettings(s){ localStorage.setItem(SETTINGS_KEY, JSON.stringify(s)); }
const settings=loadSettings(); if(geocoderSelect) geocoderSelect.value = settings.geocoder||'photon'; if(mapscoKeyInput) mapscoKeyInput.value = settings.mapscoKey||''; saveSettingsBtn?.addEventListener('click', ()=>{ const s={ geocoder: geocoderSelect.value, mapscoKey: mapscoKeyInput.value.trim() }; saveSettings(s); alert('Instellingen opgeslagen.'); });

/* Laaggroepen */
const polygonsGroup = L.featureGroup().addTo(map); const markersGroup  = L.featureGroup().addTo(map); const linesGroup    = L.featureGroup().addTo(map); const circlesGroup  = L.featureGroup().addTo(map); const handlesGroup  = L.featureGroup().addTo(map);

/* Status buttons */
btnSelftest?.addEventListener('click', async ()=>{ const okP=await testPhoton(); const okM=await testMapsCo(settings.mapscoKey); if(okP && okM) setStatus(statusGeo, 'Geocoder: Photon OK, maps.co OK', 'ok'); else if(okP) setStatus(statusGeo, 'Geocoder: alleen Photon OK', 'warn'); else if(okM) setStatus(statusGeo, 'Geocoder: alleen maps.co OK', 'warn'); else setStatus(statusGeo, 'Geocoder: geen provider OK', 'err'); });
btnResetCache?.addEventListener('click', async ()=>{ try{ if('caches' in window){ const keys=await caches.keys(); await Promise.all(keys.map(k=>caches.delete(k))); } if('serviceWorker' in navigator){ const regs = await navigator.serviceWorker.getRegistrations(); await Promise.all(regs.map(r=>r.unregister())); } localStorage.clear(); alert('Cache & service worker gereset. Herladen...'); location.reload(true); } catch(e){ console.error(e); alert('Reset mislukt, zie console.'); } });

/* Icon helpers */
function makeDivIcon(html, bg = '#1e293b', border = '#334155') { return L.divIcon({ className: 'custom-div-icon', html: `<div style="background:${bg};color:#fff;border:2px solid ${border};border-radius:12px;padding:4px 6px;font-size:14px;line-height:1;box-shadow:0 2px 6px rgba(0,0,0,.3);user-select:none;">${html}</div>`, iconSize: [32, 22], iconAnchor: [16, 11] }); }
const ICONS = { pending: () => makeDivIcon('➕', '#3b3b3b', '#555'), hoornaar: (aantal) => makeDivIcon(`🐝${aantal ? ` x${aantal}` : ''}`, '#933', '#b55'), nest: () => makeDivIcon('🪹', '#445', '#667'), nest_geruimd: () => makeDivIcon('✅', '#264', '#396'), lokpot: () => makeDivIcon('🪤', '#274', '#396') };

/* Contextmenu CSS */
let contextMenuEl=null; (function(){ const css=`.ctx-menu{position:fixed;z-index:10000;background:#111827;color:#e5e7eb;border:1px solid #374151;border-radius:8px;padding:8px;min-width:270px;max-width:340px;box-shadow:0 10px 20px rgba(0,0,0,.35);user-select:none}.ctx-menu h4{margin:4px 8px 6px;font-size:12px;color:#9ca3af;font-weight:600}.ctx-menu .row{display:flex;gap:8px;margin:6px 8px}.ctx-menu input,.ctx-menu select,.ctx-menu label{flex:1;color:#e5e7eb}.ctx-menu input,.ctx-menu select{padding:6px 8px;border-radius:6px;border:1px solid #374151;background:#0f1420}.ctx-menu .mini{font-size:12px;color:#9ca3af;margin:0 8px 6px}.ctx-menu .buttons{display:flex;gap:8px;margin:8px}.ctx-menu .buttons button{flex:1}.ctx-menu button{width:100%;display:flex;align-items:center;gap:8px;background:transparent;color:inherit;border:0;text-align:left;padding:8px 10px;border-radius:6px;font-size:14px;cursor:pointer}.ctx-menu button:hover{background:#1f2937}.ctx-menu hr{border:0;border-top:1px solid #374151;margin:6px 0}`; const s=document.createElement('style'); s.textContent=css; document.head.appendChild(s); })();
function closeContextMenu(){ if(contextMenuEl){ contextMenuEl.remove(); contextMenuEl=null; } }
function positionMenu(el,x,y){ const pad=6,vw=window.innerWidth,vh=window.innerHeight; el.style.left=Math.min(vw-el.offsetWidth-pad,Math.max(pad,x))+'px'; el.style.top=Math.min(vh-el.offsetHeight-pad,Math.max(pad,y))+'px'; setTimeout(()=>{ const c=()=>closeContextMenu(); document.addEventListener('click',c,{once:true}); window.addEventListener('blur',c,{once:true}); window.addEventListener('resize',c,{once:true}); window.addEventListener('scroll',c,{once:true}); document.addEventListener('keydown',e=>{ if(e.key==='Escape') c(); },{once:true}); },0); }

/* NL-kleuren */
const DUTCH_COLOR_MAP = new Map(Object.entries({ 'rood':'#ff0000','donkerrood':'#8b0000','lichtrood':'#ff6666','kastanjebruin':'#8b4000','bruin':'#8b4513','oranje':'#ffa500','geel':'#ffd700','goud':'#ffd700','citroengeel':'#fff44f','groen':'#008000','donkergroen':'#006400','lichtgroen':'#90ee90','lime':'#32cd32','mintgroen':'#98ff98','blauw':'#0000ff','donkerblauw':'#00008b','lichtblauw':'#87cefa','hemelsblauw':'#87ceeb','cyaan':'#00ffff','turquoise':'#40e0d0','teal':'#008080','paars':'#800080','violet':'#8a2be2','lila':'#c8a2c8','magenta':'#ff00ff','roze':'#ffc0cb','fuchsia':'#ff00ff','grijs':'#808080','lichtgrijs':'#d3d3d3','donkergrijs':'#a9a9a9','antraciet':'#2f4f4f','zilver':'#c0c0c0','zwart':'#000000','wit':'#ffffff'})); function mapDutchColor(input){ if(!input) return null; const s=String(input).trim().toLowerCase(); if(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(s)) return s; if(DUTCH_COLOR_MAP.has(s)) return DUTCH_COLOR_MAP.get(s); return s; }

/* Geocoder tests + helpers */
async function testPhoton(){ try{ const url='https://photon.komoot.io/api/?q=utrecht&limit=1'; const r=await fetch(url,{headers:{'Accept':'application/json'},mode:'cors'}); if(!r.ok) return false; const j=await r.json(); return !!j && Array.isArray(j.features); } catch(e){ return false; } }
async function testMapsCo(apiKey){ try{ const url='https://geocode.maps.co/search?q=utrecht&limit=1'+(apiKey?`&api_key=${encodeURIComponent(apiKey)}`:''); const r=await fetch(url,{headers:{'Accept':'application/json'},mode:'cors'}); if(!r.ok) return false; const j=await r.json(); return Array.isArray(j); } catch(e){ return false; } }
async function geocodePhoton(query){ const url = `https://photon.komoot.io/api/?q=${encodeURIComponent(query)}&limit=1`; const res = await fetch(url, { headers: { 'Accept': 'application/json' }, mode:'cors' }); if(!res.ok){ throw new Error(`photon HTTP ${res.status}`); } const data = await res.json(); const feat = data?.features?.[0]; if(!feat?.geometry?.coordinates) throw new Error('photon: geen resultaten'); const [lon, lat] = feat.geometry.coordinates; return {lat, lon, provider:'photon'}; }
async function geocodeMapsCo(query, apiKey){ const url = `https://geocode.maps.co/search?q=${encodeURIComponent(query)}` + (apiKey?`&api_key=${encodeURIComponent(apiKey)}`:''); const res = await fetch(url, { headers: { 'Accept': 'application/json' }, mode:'cors' }); if(!res.ok){ throw new Error(`maps.co HTTP ${res.status}`); } const data = await res.json(); if(!Array.isArray(data) || data.length===0){ throw new Error('maps.co: geen resultaten'); } const best = data[0]; const lat = parseFloat(best.lat), lon = parseFloat(best.lon); if(Number.isNaN(lat)||Number.isNaN(lon)) throw new Error('maps.co: ongeldige coördinaten'); return {lat, lon, provider:'maps.co'}; }

async function searchPlaceNL(query){ if(!query?.trim()) return; setStatus(statusGeo, 'Geocoder: zoeken…', 'warn'); const s=loadSettings(); try{ let result=null; if(s.geocoder==='photon'){ result = await geocodePhoton(query); } else if(s.geocoder==='mapsco'){ result = await geocodeMapsCo(query, s.mapscoKey); } else { // auto: eerst Photon, dan maps.co
    try{ result = await geocodePhoton(query); } catch(e1){ console.warn('Photon fout:', e1); result = await geocodeMapsCo(query, s.mapscoKey); }
  } if(result){ map.setView([result.lat, result.lon], 13); setStatus(statusGeo, `Geocoder: ${result.provider} OK`, 'ok'); }
  } catch(e){ console.error('Zoekfout:', e); const msg = /maps\.co HTTP 401/.test(String(e)) ? 'maps.co geeft 401 (API key vereist of ongeldig)' : 'provider tijdelijk onbereikbaar'; setStatus(statusGeo, `Geocoder: mislukt (${msg})`, 'err'); alert(`Zoeken mislukt: ${msg}.`); }
}
searchBtn?.addEventListener('click',()=>searchPlaceNL(placeInput.value)); placeInput?.addEventListener('keydown',e=>{ if(e.key==='Enter') searchPlaceNL(placeInput.value) });

/* Polygon labels & handlers, marker management, filters, lijnen — identiek aan 6.0.9c */
function polygonOuterRingLatLngs(layer){ let latlngs=layer.getLatLngs(); if(Array.isArray(latlngs[0])&&Array.isArray(latlngs[0][0])){latlngs=latlngs[0][0]} else if(Array.isArray(latlngs[0])){latlngs=latlngs[0]} return latlngs }
function centroidOfLatLngs(latlngs){ if(!latlngs||latlngs.length<3) return null; let area=0,cx=0,cy=0; for(let i=0,j=latlngs.length-1;i<latlngs.length;j=i++){ const x0=latlngs[j].lng,y0=latlngs[j].lat; const x1=latlngs[i].lng,y1=latlngs[i].lat; const f=x0*y1-x1*y0; area+=f; cx+=(x0+x1)*f; cy+=(y0+y1)*f; } area*=0.5; if(Math.abs(area)<1e-12) return null; cx/=(6*area); cy/=(6*area); return L.latLng(cy,cx) }
function makeLabelIcon(text,color='#0aa879'){ const safe=(text??'').toString().replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); return L.divIcon({className:'poly-label-marker',html:`<div style="background:rgba(0,0,0,0.55);border:1px solid ${color};color:#e6eef5;padding:3px 6px;border-radius:6px;font-size:12px;line-height:1.2;backdrop-filter:blur(2px);user-select:none;white-space:nowrap;">${safe}</div>`,iconSize:null}) }
function ensureLabelMarker(layer){ const props=layer._props||{}; if(!props.label){ if(layer._labelMarker){ map.removeLayer(layer._labelMarker); layer._labelMarker=null } return } let pos=props.labelPos?L.latLng(props.labelPos.lat,props.labelPos.lng):null; if(!pos||!props.labelManual){ const outer=polygonOuterRingLatLngs(layer); let c=centroidOfLatLngs(outer); if(!c) c=layer.getBounds().getCenter(); pos=c; if(!props.labelManual) props.labelPos={lat:pos.lat,lng:pos.lng} } const icon=makeLabelIcon(props.label,props.color||'#0aa879'); if(!layer._labelMarker){ const m=L.marker(pos,{icon,draggable:true,keyboard:false,zIndexOffset:1000}).addTo(map); m.on('dragend',()=>{ const ll=m.getLatLng(); layer._props.labelPos={lat:ll.lat,lng:ll.lng}; layer._props.labelManual=true }); layer._labelMarker=m } else { layer._labelMarker.setIcon(icon); layer._labelMarker.setLatLng(pos) } }
function refreshLabelMarker(layer){ if(!layer?._props?.label){ if(layer._labelMarker){ map.removeLayer(layer._labelMarker); layer._labelMarker=null } return } ensureLabelMarker(layer) }
function attachPolygonHandlers(layer){ layer.setStyle({color:'#0aa879',fillColor:'#0aa879',fillOpacity:0.2,weight:2}); layer._props = layer._props || { label:'', color:'#0aa879', labelPos:null, labelManual:false }; ensureLabelMarker(layer); layer.on('contextmenu',(e)=>{ e.originalEvent?.preventDefault(); e.originalEvent?.stopPropagation(); if (debounceEvent()) return; openPolygonContextMenu(layer, e.originalEvent?.clientX??0, e.originalEvent?.clientY??0, e.latlng); }); layer.on('click',(e)=>{ e.originalEvent?.preventDefault(); e.originalEvent?.stopPropagation(); if (debounceEvent()) return; openPolygonContextMenu(layer, e.originalEvent?.clientX??0, e.originalEvent?.clientY??0, e.latlng); }); const auto=()=>{ if(!layer._props?.label || layer._props.labelManual) return; const outer=polygonOuterRingLatLngs(layer); let c=centroidOfLatLngs(outer)||layer.getBounds().getCenter(); layer._props.labelPos={lat:c.lat,lng:c.lng}; refreshLabelMarker(layer) }; layer.on('pm:edit', auto); layer.on('pm:dragend', auto); layer.on('remove', ()=>{ if(layer._labelMarker){ map.removeLayer(layer._labelMarker); layer._labelMarker=null } }); }
map.on('pm:create', e=>{ const layer=e.layer; if(e.shape==='Polygon' || e.shape==='Rectangle'){ polygonsGroup.addLayer(layer); attachPolygonHandlers(layer) } else { layer.remove() } });

let allMarkers = [];
const FILTERS_KEY = 'hornet_filters_v609d';
const filterEls = { hoornaar: document.getElementById('f_type_hoornaar'), nest: document.getElementById('f_type_nest'), nest_geruimd: document.getElementById('f_type_nest_geruimd'), lokpot: document.getElementById('f_type_lokpot'), pending: document.getElementById('f_type_pending'), linesVisible: document.getElementById('f_lines_visible'), dateBefore: document.getElementById('f_date_before') };
function loadFilters(){ try{ const raw=localStorage.getItem(FILTERS_KEY); if(!raw) return null; return JSON.parse(raw); } catch{ return null; } }
function saveFilters(obj){ localStorage.setItem(FILTERS_KEY, JSON.stringify(obj)); }
function getActiveFilters(){ return { hoornaar: !!filterEls.hoornaar?.checked, nest: !!filterEls.nest?.checked, nest_geruimd: !!filterEls.nest_geruimd?.checked, lokpot: !!filterEls.lokpot?.checked, pending: !!filterEls.pending?.checked, linesVisible: !!filterEls.linesVisible?.checked, dateBefore: filterEls.dateBefore?.value || '' }; }
function restoreFilterUI(){ const f=loadFilters(); if(!f) return; if(filterEls.hoornaar) filterEls.hoornaar.checked = !!f.hoornaar; if(filterEls.nest) filterEls.nest.checked = !!f.nest; if(filterEls.nest_geruimd) filterEls.nest_geruimd.checked = !!f.nest_geruimd; if(filterEls.lokpot) filterEls.lokpot.checked = !!f.lokpot; if(filterEls.pending) filterEls.pending.checked = !!f.pending; if(filterEls.linesVisible) filterEls.linesVisible.checked = (f.linesVisible!==false); if(filterEls.dateBefore) filterEls.dateBefore.value = f.dateBefore || ''; }
function markerMatchesFilters(marker, filters){ const meta=marker._meta||{}; const t=meta.type||'pending'; if(!filters[t]) return false; const db=filters.dateBefore; if(db){ const md=meta.date; if(md && md < db) return false; } return true; }
function applyFilters(){ const filters=getActiveFilters(); saveFilters(filters); allMarkers.forEach(m=>{ const shouldShow = markerMatchesFilters(m, filters); const inGroup = markersGroup.hasLayer(m); if(shouldShow && !inGroup){ markersGroup.addLayer(m); } else if(!shouldShow && inGroup){ markersGroup.removeLayer(m); } }); const visiblePotIds=new Set(); allMarkers.forEach(m=>{ const mm=m._meta||{}; if(mm.type==='lokpot'){ if(markersGroup.hasLayer(m)) visiblePotIds.add(mm.id); }}); const showLines=!!filters.linesVisible; allLines.forEach(line=>{ const meta=line._meta||{}; const should=showLines && visiblePotIds.has(meta.potId); const onMap=linesGroup.hasLayer(line); if(should && !onMap){ linesGroup.addLayer(line); } else if(!should && onMap){ linesGroup.removeLayer(line); } }); allSectors.forEach(sec=>{ const meta=sec._meta||{}; const potId=meta.pot?.id || meta.potId; const should=showLines && visiblePotIds.has(potId); const onMap=circlesGroup.hasLayer(sec); if(should && !onMap){ circlesGroup.addLayer(sec); } else if(!should && onMap){ circlesGroup.removeLayer(sec); } }); }
applyFiltersBtn?.addEventListener('click', applyFilters); resetFiltersBtn?.addEventListener('click', ()=>{ if(filterEls.hoornaar) filterEls.hoornaar.checked=true; if(filterEls.nest) filterEls.nest.checked=true; if(filterEls.nest_geruimd) filterEls.nest_geruimd.checked=true; iffilterEls?.lokpot && (filterEls.lokpot.checked=true); if(filterEls.pending) filterEls.pending.checked=true; if(filterEls.linesVisible) filterEls.linesVisible.checked=true; if(filterEls.dateBefore) filterEls.dateBefore.value=''; applyFilters(); }); restoreFilterUI();

function placeMarkerAt(latlng, type='pending'){ if(!latlng) return null; let marker; if(type==='hoornaar'){ marker=L.marker(latlng,{icon:ICONS.hoornaar()}); marker._meta={type}; } else if(type==='nest'){ marker=L.marker(latlng,{icon:ICONS.nest()}); marker._meta={type}; } else if(type==='nest_geruimd'){ marker=L.marker(latlng,{icon:ICONS.nest_geruimd()}); marker._meta={type}; } else if(type==='lokpot'){ marker=L.marker(latlng,{icon:ICONS.lokpot()}); marker._meta={type,id:`pot_${Date.now()}_${Math.random().toString(36).slice(2)}`}; } else { marker=L.marker(latlng,{icon:ICONS.pending()}); marker._meta={type:'pending'}; } attachMarkerPopup(marker); allMarkers.push(marker); if(markerMatchesFilters(marker, getActiveFilters())) markersGroup.addLayer(marker); return marker; }
map.on('click',(e)=>{ if (debounceEvent()) return; const m=placeMarkerAt(e.latlng,'pending'); if(m){ openMarkerContextMenu(m, e.originalEvent?.clientX??0, e.originalEvent?.clientY??0); } }); map.on('contextmenu',(e)=>{ if (debounceEvent()) return; openMapContextMenu(e.latlng, e.originalEvent?.clientX??0, e.originalEvent?.clientY??0); });
function openMapContextMenu(latlng, x, y){ closeContextMenu(); const el=document.createElement('div'); el.className='ctx-menu'; el.innerHTML=`<h4>Nieuw icoon hier</h4>
<button data-type="hoornaar">🐝 Waarneming</button>
<button data-type="nest">🪹 Nest</button>
<button data-type="nest_geruimd">✅ Nest geruimd</button>
<button data-type="lokpot">🪤 Lokpot</button>`; el.addEventListener('contextmenu',e=>e.preventDefault()); el.addEventListener('click',e=>e.stopPropagation()); el.addEventListener('click',ev=>{ const b=ev.target.closest('button'); if(!b) return; const type=b.dataset.type; closeContextMenu(); setTimeout(()=>{ const m = placeMarkerAt(latlng, type||'pending'); if(m) { openMarkerContextMenu(m, x, y); } },0); }); document.body.appendChild(el); contextMenuEl=el; positionMenu(el,x,y); }
function openMarkerContextMenu(marker, x, y){ closeContextMenu(); const el=document.createElement('div'); el.className='ctx-menu'; el.innerHTML=`<h4>Icoon</h4>
<button data-act="set_type" data-type="hoornaar">🐝 Waarneming</button>
<button data-act="set_type" data-type="nest">🪹 Nest</button>
<button data-act="set_type" data-type="nest_geruimd">✅ Nest geruimd</button>
<button data-act="set_type" data-type="lokpot">🪤 Lokpot</button>
<hr/>
<button data-act="props">✏️ Eigenschappen</button>
<button data-act="zender">📡 Zender actie</button>
<button data-act="delete">🗑️ Verwijderen</button>`; el.addEventListener('contextmenu',e=>e.preventDefault()); el.addEventListener('click',e=>e.stopPropagation()); el.addEventListener('click',ev=>{ const btn=ev.target.closest('button'); if(!btn) return; const act=btn.dataset.act; closeContextMenu(); setTimeout(()=>{ if(act==='set_type'){ setMarkerType(marker, btn.dataset.type, true); } else if(act==='props'){ editMarkerProps(marker); } else if(act==='zender'){ const mm=marker._meta||{}; if(mm.type!=='lokpot'){ alert('Zender actie is alleen beschikbaar voor een lokpot.'); return; } const ok = hasFlightForPot(mm.id); if(!ok){ alert('Nog geen richting en afstand bepaald'); return; } openZenderChecklist(marker, x, y); } else if(act==='delete'){ if ((marker._meta||{}).type==='lokpot' && marker._meta.id) { removePotAssociations(marker._meta.id); } markersGroup.removeLayer(marker); allMarkers = allMarkers.filter(m=>m!==marker); applyFilters(); } },0); }); document.body.appendChild(el); contextMenuEl=el; positionMenu(el,x,y); }
function attachMarkerPopup(marker, refreshOnly=false){ const meta=marker._meta||{}; marker.on('click',e=>{ e.originalEvent?.preventDefault(); e.originalEvent?.stopPropagation(); }); marker.on('contextmenu',e=>{ e.originalEvent?.preventDefault(); e.originalEvent?.stopPropagation(); if (debounceEvent()) return; openMarkerContextMenu(marker, e.originalEvent?.clientX??0, e.originalEvent?.clientY??0); }); if(meta.type==='lokpot'){ marker.bindPopup(()=>{ const container=document.createElement('div'); const mm=marker._meta||{}; const dateLine = mm.date? `<div>Datum: ${mm.date}${mm.by?` — door ${mm.by}`:''}</div>`:''; let zenderLine=''; const z=mm.zender_actie||{}; const lines=[]; if(z.gepland) lines.push('Gepland/gedaan: ja'); if(z.zender_geplaatst) lines.push(`Zender geplaatst${z.zender_geplaatst_datum?`: ${z.zender_geplaatst_datum}`:''}`); if(z.signaal_ontvangen) lines.push(`Signaal ontvangen${z.signaal_ontvangen_datum?`: ${z.signaal_ontvangen_datum}`:''}`); if(z.nest_gevonden) lines.push(`Nest gevonden${z.nest_gevonden_datum?`: ${z.nest_gevonden_datum}`:''}`); if(z.nest_bestreden) lines.push(`Nest bestreden${z.nest_bestreden_datum?`: ${z.nest_bestreden_datum}`:''}`); if(z.zender_teruggevonden) lines.push(`Zender teruggevonden${z.zender_teruggevonden_datum?`: ${z.zender_teruggevonden_datum}`:''}`); if(z.wie_helpen) lines.push(`Wie helpen: ${z.wie_helpen}`); if(lines.length){ zenderLine = `<div><b>Zender actie</b><br/>${lines.join('<br/>')}</div>`; } container.innerHTML=`<b>Lokpot</b>${dateLine}${zenderLine?('<br/>'+zenderLine):''}<br/><button id="new-line-btn" style="margin-top:6px;">Nieuwe vlieglijn</button>`; setTimeout(()=>{ const btn=container.querySelector('#new-line-btn'); btn?.addEventListener('click',()=> startFlightLine(marker)); },0); return container; }); } else if(meta.type==='hoornaar'){ const parts=[]; parts.push(meta.aantal?`Waarneming (x${meta.aantal})`:'Waarneming'); if(meta.date) parts.push(`Datum: ${meta.date}${meta.by?` — door ${meta.by}`:''}`); marker.bindPopup(parts.join('<br/>')); } else if(meta.type==='nest'){ const parts=['Nest waargenomen']; if(meta.date) parts.push(`Datum: ${meta.date}${meta.by?` — door ${meta.by}`:''}`); marker.bindPopup(parts.join('<br/>')); } else if(meta.type==='nest_geruimd'){ const parts=['Nest geruimd']; if(meta.date) parts.push(`Datum: ${meta.date}${meta.by?` — door ${meta.by}`:''}`); marker.bindPopup(parts.join('<br/>')); } else { marker.bindPopup('Nieuw icoon — rechtermuisklik om type/eigenschappen te kiezen'); } if(!refreshOnly){ marker.openPopup?.(); } }
function editMarkerProps(marker){ const meta=marker._meta||{}; const when=prompt('Datum (YYYY-MM-DD):', meta.date || new Date().toISOString().slice(0,10)); if(when===null) return; const by=prompt('Door wie:', meta.by || ''); if(by===null) return; if(meta.type==='hoornaar'){ const a=prompt('Aantal waarnemingen (optioneel):', meta.aantal ?? ''); if(a===null) return; const aantal=a ? (parseInt(a,10)||undefined) : undefined; meta.aantal=aantal; marker.setIcon(ICONS.hoornaar(aantal)); } meta.date=when||undefined; meta.by=by||undefined; if(meta.type==='lokpot') marker.setIcon(ICONS.lokpot()); if(meta.type==='nest') marker.setIcon(ICONS.nest()); if(meta.type==='nest_geruimd') marker.setIcon(ICONS.nest_geruimd()); marker._meta=meta; attachMarkerPopup(marker, true); }
function setMarkerType(marker,newType, askProps=false){ const oldMeta=marker._meta||{}; let meta={...oldMeta, type:newType}; if(newType==='lokpot' && !meta.id) meta.id=`pot_${Date.now()}_${Math.random().toString(36).slice(2)}`; if(oldMeta.type==='lokpot' && newType!=='lokpot' && oldMeta.id) removePotAssociations(oldMeta.id); if(askProps){ const d=prompt('Datum (YYYY-MM-DD):', meta.date || new Date().toISOString().slice(0,10)); if(d===null) return; const w=prompt('Door wie:', meta.by || ''); if(w===null) return; meta.date=d||undefined; meta.by=w||undefined; if(newType==='hoornaar'){ const a=prompt('Aantal waarnemingen (optioneel):', meta.aantal ?? ''); if(a===null) return; const aantal=a ? (parseInt(a,10)||undefined) : undefined; meta.aantal=aantal; } else { delete meta.aantal; } if(newType==='lokpot'){ meta.zender_actie = meta.zender_actie || { gepland:false }; } } if(newType==='hoornaar'){ marker.setIcon(ICONS.hoornaar(meta.aantal)); } else if(newType==='nest'){ marker.setIcon(ICONS.nest()); } else if(newType==='nest_geruimd'){ marker.setIcon(ICONS.nest_geruimd()); } else if(newType==='lokpot'){ marker.setIcon(ICONS.lokpot()); } else { marker.setIcon(ICONS.pending()); } marker._meta=meta; attachMarkerPopup(marker, true); applyFilters(); }
function startFlightLine(lokpotMarker){ lokpotMarker.closePopup(); const potLatLng=lokpotMarker.getLatLng(); const potId=(lokpotMarker._meta||{}).id; const tempLine=L.polyline([potLatLng,potLatLng],{color:'#ffcc00',weight:3,dashArray:'5 4'}).addTo(map); function onMove(e){ tempLine.setLatLngs([potLatLng, e.latlng]); } function finish(e){ map.off('mousemove', onMove); map.off('click', finish); tempLine.remove(); const clicked=e.latlng; let dist=prompt('Afstand tot nest (meter):','200'); if(dist===null) return; dist=Math.max(1, parseInt(dist,10) || 1); const defaultColor='#ffcc00'; const bearing=bearingBetween(potLatLng, clicked); const endLatLng=destinationPoint(potLatLng, dist, bearing); const flightId=`flight_${Date.now()}_${Math.random().toString(36).slice(2)}`; const line=L.polyline([potLatLng, endLatLng],{color:defaultColor,weight:3}).addTo(linesGroup); line._meta={type:'flight',pot:{lat:potLatLng.lat,lng:potLatLng.lng,id:potId},potId:potId,distance:dist,color:defaultColor,bearing,flightId}; registerLine(line); line.bindTooltip(`${dist} m`,{permanent:true,direction:'center',className:'line-label'}); const rInner=Math.max(1,dist-25), rOuter=dist+25; const sector=createSectorLayer({pot:{lat:potLatLng.lat,lng:potLatLng.lng,id:potId},distance:dist,color:defaultColor,bearing,rInner,rOuter,angleLeft:45,angleRight:45,steps:36,flightId}).addTo(circlesGroup); registerSector(sector); line._sector=sector; sector._line=line; attachFlightInteractivity(line); applyFilters(); } map.on('mousemove', onMove); map.on('click', finish); }

/* Opslaan / Laden */
const STORAGE_KEY = 'hornet-mapper-nl-v6.0.9d'; function serialize(){ const polygons=[]; polygonsGroup.eachLayer(layer=>{ const gj=layer.toGeoJSON(); polygons.push({ geojson:gj, props:layer._props || { label:'', color:'#0aa879', labelPos:null, labelManual:false } }); }); const markers=[]; allMarkers.forEach(m=>{ const {lat,lng}=m.getLatLng(); const meta=m._meta||{}; markers.push({ lat, lng, meta }); }); const lines=[]; allLines.forEach(l=>{ const latlngs=l.getLatLngs(); const meta=l._meta||{}; lines.push({ coords:latlngs.map(ll=>({lat:ll.lat, lng:ll.lng})), meta }); }); const circles=[]; allSectors.forEach(s=>{ circles.push(s._meta||{}); }); return { version:6.09, polygons, markers, lines, circles }; } function clearAll(){ polygonsGroup.clearLayers(); markersGroup.clearLayers(); linesGroup.clearLayers(); circlesGroup.clearLayers(); handlesGroup.clearLayers(); allMarkers=[]; allLines=[]; allSectors=[]; } function restore(state){ clearAll(); if(!state) return; (state.polygons||[]).forEach(({geojson, props})=>{ const layer=L.geoJSON(geojson).getLayers()[0]; polygonsGroup.addLayer(layer); layer._props={ label:props?.label||'', color:props?.color||'#0aa879', labelPos:props?.labelPos||null, labelManual:!!props?.labelManual }; attachPolygonHandlers(layer); const color=layer._props.color||'#0aa879'; layer.setStyle({ color, fillColor:color, fillOpacity:0.2, weight:2 }); refreshLabelMarker(layer); }); const linesById={}; (state.lines||[]).forEach(({coords, meta})=>{ const line=L.polyline(coords.map(c=>[c.lat,c.lng]),{ color:meta?.color||'#ffcc00', weight:3 }).addTo(linesGroup); line._meta=meta||{}; registerLine(line); if(meta?.distance){ line.bindTooltip(`${meta.distance} m`,{ permanent:true, direction:'center', className:'line-label' }); } if(meta?.type==='flight'){ linesById[meta.flightId||('noid_'+Math.random())]=line; } attachFlightInteractivity(line); }); (state.circles||[]).forEach(meta=>{ if(meta?.type==='sector'){ const sector=createSectorLayer(meta).addTo(circlesGroup); registerSector(sector); if(meta.flightId && linesById[meta.flightId]){ const ln=linesById[meta.flightId]; ln._sector=sector; sector._line=ln; } } else if(meta?.pot && meta?.distance){ const circle=L.circle([meta.pot.lat,meta.pot.lng],{radius:meta.distance,color:meta.color||'#ffcc00',weight:1,dashArray:'6 8',fillOpacity:0}).addTo(circlesGroup); circle._meta=meta; registerSector(circle); } }); (state.markers||[]).forEach(({lat,lng,meta})=>{ let marker; if(meta?.type==='hoornaar'){ marker=L.marker([lat,lng],{icon:ICONS.hoornaar(meta.aantal)}); } else if(meta?.type==='nest'){ marker=L.marker([lat,lng],{icon:ICONS.nest()}); } else if(meta?.type==='nest_geruimd'){ marker=L.marker([lat,lng],{icon:ICONS.nest_geruimd()}); } else if(meta?.type==='lokpot'){ marker=L.marker([lat,lng],{icon:ICONS.lokpot()}); } else { marker=L.marker([lat,lng],{icon:ICONS.pending()}); } marker._meta=meta||{}; attachMarkerPopup(marker); allMarkers.push(marker); }); applyFilters(); }
saveBtn?.addEventListener('click', ()=>{ const state=serialize(); localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); alert('Opgeslagen in je browser (localStorage).'); }); loadBtn?.addEventListener('click', ()=>{ const raw=localStorage.getItem(STORAGE_KEY); if(!raw) return alert('Geen lokale data gevonden.'); try{ const state=JSON.parse(raw); restore(state); } catch{ alert('Laden mislukt: beschadigde data.'); } }); exportBtn?.addEventListener('click', ()=>{ const state=serialize(); const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`hornet-mapper-${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(a.href); }); importFile?.addEventListener('change', async e=>{ const file=e.target.files?.[0]; if(!file) return; const text=await file.text(); try{ const state=JSON.parse(text); restore(state); alert('Data geïmporteerd.'); } catch{ alert('Import mislukt: geen geldige JSON.'); } finally{ importFile.value=''; } }); clearBtn?.addEventListener('click', ()=>{ if (confirm('Weet je zeker dat je alles wilt wissen?')){ localStorage.removeItem(STORAGE_KEY); clearAll(); } });

if (typeof L==='undefined') { console.error('Leaflet (L) is NIET beschikbaar.'); } else { console.log('Leaflet (L) is beschikbaar:', L.version); }
